// <auto-generated />
using System;
using DataPlus.Bar.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataPlus.Bar.Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20191012155235_updateModel")]
    partial class updateModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("DocumentNumber");

                    b.Property<int>("DocumentType");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category");

                    b.Property<string>("Name");

                    b.Property<int>("Presentation");

                    b.Property<float>("Quantity");

                    b.Property<float>("Value");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Level");

                    b.Property<string>("Logger");

                    b.Property<string>("Message");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<Guid?>("ClientId1");

                    b.Property<DateTime>("Date");

                    b.Property<int>("PaymentId");

                    b.Property<Guid?>("PaymentId1");

                    b.Property<int>("PaymentStatus");

                    b.Property<int>("TableId");

                    b.Property<Guid?>("TableId1");

                    b.Property<long>("Total");

                    b.Property<string>("Waiter");

                    b.HasKey("ID");

                    b.HasIndex("ClientId1");

                    b.HasIndex("PaymentId1");

                    b.HasIndex("TableId1");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Cost");

                    b.Property<bool>("IsPrinted");

                    b.Property<string>("Observation");

                    b.Property<int>("OldQuantity");

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.Property<int>("Quantity");

                    b.Property<long>("Total");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cashier");

                    b.Property<float>("Change");

                    b.Property<float>("Credit");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Discount");

                    b.Property<string>("Iterator");

                    b.Property<long>("Number");

                    b.Property<int>("PaymentStatus");

                    b.Property<string>("Prefix");

                    b.Property<float>("Receive");

                    b.Property<float>("ReceiveCard");

                    b.Property<float>("Total");

                    b.Property<string>("Voucher");

                    b.HasKey("Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("CostPrice");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("SalePrice");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Table", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Chairs");

                    b.Property<string>("Number");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.Order", b =>
                {
                    b.HasOne("DataPlus.Bar.Entities.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId1");

                    b.HasOne("DataPlus.Bar.Entities.Models.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId1");

                    b.HasOne("DataPlus.Bar.Entities.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId1");
                });

            modelBuilder.Entity("DataPlus.Bar.Entities.Models.OrderItem", b =>
                {
                    b.HasOne("DataPlus.Bar.Entities.Models.Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
